stages:
  - build
  - deploy

build:
  stage: build
  image: node:lts
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y openssh-client
  script:
    - 'which ssh-agent || (apt-get install -y openssh-client)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts'
    - scp -r -o StrictHostKeyChecking=no build/ $SSH_USER@$SSH_HOST:/var/www/html/
