image: node:14

stages:
  - build
  - package
  - deploy

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build

package:
  stage: package
  script:
    - mkdir artifacts
    - tar -czvf artifacts/app.tar.gz build/

deploy:
  stage: deploy
  script:
    - apt-get install -y sshpass
    - sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no artifacts/app.tar.gz $SSH_USER@$SSH_HOST:/home/$SSH_USER
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "sudo rm -rf /var/www/html/*"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "sudo tar -xzvf /home/$SSH_USER/app.tar.gz -C /var/www/html"
