stages:
  - build
  - deploy

build:
  stage: build
  image: node:lts
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y openssh-client
  script:
    - 'which ssh-agent || (apt-get install -y openssh-client)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 400 $id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - apt-get update -y
    - apt-get -y install rsync
    - '[[ -f /.dockerenv ]] && echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts'
    - scp -r -i $id_rsa build/ $SSH_USER@$SSH_HOST:/var/www/html/
