image: node:14

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  image: python:latest
  script:
    - apt-get update -qq && apt-get install -y -qq python3-pip
    - pip3 install --upgrade awscli
    - pip3 install --upgrade awsebcli
    - echo "DEPLOYMENT_ENV=production" >> .env
    - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
    - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
    - echo "AWS_REGION=us-east-1" >> .env
    - eb init -r us-east-1 -p "Node.js 14" React-GitLab
    - eb deploy
  only:
    - main

