image: node:14

stages:
  - build
  - package
  - deploy

build:
  stage: build
  before_script:
  - npm install
  script:
    - npm run build

package:
  stage: package
  script:
    - mkdir artifacts
    - tar -czvf artifacts/app.tar.gz build/

deploy:
  stage: deploy
  script:
    deploy:
  stage: deploy
  script:
    - apt-get install -y openssh-client
    - scp -o StrictHostKeyChecking=no -r build/ $SSH_USER@$SSH_HOST:/var/www/html/
